import { Router } from 'express';
import { createAlertSchema, paperOrderSchema } from '@marketpulse/shared';
import * as auth from '../controllers/auth.controller.js';
import * as broker from '../controllers/broker.controller.js';
import * as dashboard from '../controllers/dashboard.controller.js';
import * as intel from '../controllers/intelligence.controller.js';
import * as alerts from '../controllers/alert.controller.js';
import * as paper from '../controllers/paper.controller.js';
import * as admin from '../controllers/admin.controller.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { validateBody } from '../middleware/validate.js';
import { loginSchema, registerSchema } from '../services/auth.service.js';

export const router = Router();
router.get('/health', (_req, res) => res.json({ ok: true, service: 'marketpulse-api' }));
router.post('/auth/register', validateBody(registerSchema), auth.register);
router.post('/auth/login', validateBody(loginSchema), auth.login);
router.get('/auth/me', requireAuth, auth.me);
router.get('/dashboard', requireAuth, dashboard.getDashboard);
router.post('/brokers/:broker/oauth/callback', requireAuth, broker.oauthCallback);
router.post('/brokers/sync', requireAuth, broker.sync);
router.get('/news', requireAuth, intel.news);
router.get('/corporate-actions', requireAuth, intel.corporateActions);
router.get('/insider-trades', requireAuth, intel.insiderTrades);
router.get('/themes', requireAuth, intel.themes);
router.get('/earnings', requireAuth, intel.earnings);
router.get('/social-sentiment', requireAuth, intel.social);
router.get('/portfolio/health', requireAuth, intel.health);
router.get('/tax/loss-harvesting', requireAuth, intel.tax);
router.get('/alerts', requireAuth, alerts.listAlerts);
router.post('/alerts', requireAuth, validateBody(createAlertSchema), alerts.createAlert);
router.get('/paper/portfolio', requireAuth, paper.paperPortfolio);
router.post('/paper/orders', requireAuth, validateBody(paperOrderSchema), paper.placePaperOrder);
router.get('/admin/summary', requireAuth, requireRole(['admin']), admin.adminSummary);
